### ISSUE TITLE
Multiple limits

### ISSUE THREAD

**Issue by stgleb** [joncalhoun/drip#1]
This is a nice idea, I came to the same when thought about rate limiting. But what if you've got multiple limits? Like show something once per second, but only 10 times per minute, 300 per hour and 3000 per day?

**Comment by joncalhoun** [comment]
Honestly this isn't a great solution long term and was intended for learning and I only ever used it on a small side project. With that in mind, you *could* use multiple buckets and verify that all have capacity to solve the problem you are describing. 

Eg one bucket with capacity 1 and interval of 1s, another with capacity of 10 and an interval of 10m, etc. Then you would just need to iterate over all buckets and make sure you can consume all of them. The code there now wouldn't work for this, but you could likely make it work by adding a `CanConsume(int) bool` method. 

There are other issues tho, like persisting bucket capacity somewhere and making this work across multiple machines or goroutines. Again, a very experimental and limited library here :)

**Comment by stgleb** [comment]
I agree, but there is another problem. if you've got enough limit per second and minute, but per hour limit is exceed and you have to rollback tokens that you've got from previous limits. This is complicated stuff and should be done in transaction manner. I've just opened this issue to share my thoughts about the problem, currently I've implemented compund limits per resource with redis lua script.

**Comment by joncalhoun** [comment]
That is why I had initially suggested the `CanConsume()` method - it would help alleviate some of this, but depending on your use case it might not be sufficient. Do you have a particular API or something in mind that uses limits like this? It seems a bit overkill to define API rate limits on so many granular levels.

**Comment by stgleb** [comment]
Yes, I have. I working on advertising system and I should impose limits on ad show. There might be limits per second, minute, hour, day and total and all limits should be satisfied. Also `CanConsume`  is hard to implement since there is no method to check that channel is ready to read without blocking.
